package com.waypoint.user.auth.exception;

import lombok.Getter;

@Getter
public enum ErrorMessage {
  MANDATORY_FIELDS_MISSING(422, "MANDATORY_FIELDS_MISSING", "MANDATORY FIELDS MISSING IN PAYLOAD"),
  LOGIN_FAILED(422, "INCORRECT_LOGIN_CREDENTIALS", "INCORRECT LOGIN CREDENTIALS"),
  SIGNUP_FAILED(500, "USER_SIGNUP_FAILED", "ERROR WHILE PROCESSING SIGNUP REQUEST"),
  INVALID_OTP(500, "INVALID_OTP", "INCORRECT OTP"),
  FAILED_TO_SEND_OTP(500, "FAILED_TO_SEND_OTP", "FAILED TO SEND OTP"),
  USERNAME_NOT_AVAILABLE(
      422, "USERNAME_NOT_AVAILABLE", "PROVIDED USERNAME IS LINKED TO ANOTHER ACCOUNT"),
  USERNAME_EMAIL_NOT_FOUND(422, "USERNAME_EMAIL_NOT_FOUND", "PROVIDED USERNAME AND EMAIL DOESN'T EXIST"),
  USERNAME_NOT_FOUND(422, "USERNAME_NOT_FOUND", "PROVIDED USERNAME DOESN'T EXIST"),
  EMAIL_NOT_FOUND(422, "EMAIL_NOT_FOUND", "PROVIDED EMAIL DOESN'T EXIST"),
  USER_TRIP_MAPPING_FAILED(500, "USER_TRIP_MAPPING_FAILED", "ERROR WHILE SAVING USER TRIP MAPPING"),
  USER_TRIP_MAPPING_NOT_FOUND(500, "USER_TRIP_MAPPING_NOT_FOUND", "NO MAPPING FOUND FOR USER AND TRIP"),
  INVALID_PASSWORD(422, "INVALID_PASSWORD", "NEW PASSWORD CANNOT BE SAME AS OLD PASSWORD"),
  UNAUTHORIZED(401, "UNAUTHORIZED", "UNAUTHORIZED");
  private final int httpStatusCode;
  private final String messageCode;
  private final String messageDescription;

  ErrorMessage(int httpStatusCode, String messageCode, String messageDescription) {
    this.httpStatusCode = httpStatusCode;
    this.messageCode = messageCode;
    this.messageDescription = messageDescription;
  }
}
