CREATE TABLE USER_DETAILS (
ID UUID DEFAULT "user".uuid_generate_v4(),
USER_ID VARCHAR(50) NOT NULL,
FIRST_NAME VARCHAR(50),
MIDDLE_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
EMAIL VARCHAR(50) NOT NULL,
MOBILE_NO VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
SECRET VARCHAR(400),
MFA BOOLEAN,
CONSTRAINT USER_ID_UNIQUE UNIQUE (USER_ID),
CONSTRAINT USER_PKEY PRIMARY KEY (ID)
);